{% set version = "0.22.0" %}

channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults

package:
  name: pysam
  version: {{ version }}

source:
  url: https://github.com/pysam-developers/pysam/archive/v{{ version }}.tar.gz

build:
  number: 0
  noarch: generic

requirements:
  build:
    - python >=3.10
    - setuptools
    - zlib
    - cython
  run:
    - python >=3.10
    - zlib
    - xz
    - bzip2
    - htslib

test:
  imports:
    - pysam

about:
  home: https://github.com/pysam-developers/pysam
  license: MIT
  summary: Pysam is a python module for reading and manipulating Samfiles. It's a lightweight wrapper of the samtools C-API. Pysam also includes an interface for tabix.

